Trying to change the group name to an already existing name now fails
ghga-de/datameta pull request #236
Opened 2021-03-25 17:40 UTC by MoritzHahn1337

2021-03-25 20:34 UTC, lkuchenb reviewed
We should be enforcing this in the database model

2021-03-26 08:51 UTC, lkuchenb commented
@MoritzHahn1337 I've pushed the DB change against this branch. Could you change the handling in the backend function such that it now catches the database error?

2021-03-26 13:04 UTC, MoritzHahn1337 commented
Will do, but probably won't get to it until monday

2021-04-13 11:56 UTC, MoritzHahn1337 commented
When trying to change the database via a db.commit(),  a `sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation)` is thrown. As db.commit() is executed on a return statement, I expected `try: ... except: ...` to catch the error, but it does not:

```
try:
    target_group.name = new_group_name
    return HTTPNoContent()
except:
    response_body = []
    err["message"] = "This group name does already exist."
    response_body.append(err)
    raise HTTPBadRequest(json=response_body)```
    
Still throws the same error.

2021-04-13 12:43 UTC, MoritzHahn1337 commented
After trying some more, I did not find an easy way to catch a database error and reverted to catching a naming collision manually for the time beeing.

2021-04-13 14:04 UTC, MoritzHahn1337 commented
db.flush() did do the trick.

2021-04-13 22:01 UTC, cschu commented on tests/integration/test_groupnameupdate.py
> +        # this throws an IntegrityError instead of 400
```suggestion

```

2021-04-13 22:01 UTC, cschu commented on tests/integration/test_groupnameupdate.py
> +        # this throws an IntegrityError instead of 400
no longer the case :)

2021-04-14 09:58 UTC, lkuchenb requested changes
Thanks, looks good to me. One minor fix request below.

2021-04-14 09:58 UTC, lkuchenb commented on datameta/api/groups.py
> +            raise HTTPBadRequest(json=response_body)
```suggestion
            raise errors.get_validation_error("A group with that name already exists.")
```

2021-04-14 12:00 UTC, lkuchenb approved these changes
Good to go!

2021-04-14 14:13 UTC, merged