Bulkdelete frontend
ghga-de/datameta pull request #296
Opened 2021-04-20 11:28 UTC by MoritzHahn1337

2021-04-20 17:39 UTC, MoritzHahn1337 commented
Should fix
#280
#221

2021-04-20 21:14 UTC, cschu approved these changes

2021-04-21 08:37 UTC, lkuchenb requested changes
Thanks!

2021-04-21 08:37 UTC, lkuchenb commented on datameta/static/js/submit.js
> +    }).then(function(json) {
Same as above

2021-04-21 08:37 UTC, lkuchenb commented on datameta/static/js/submit.js
> +DataMeta.submit.deleteSelectedFiles = function() {
Please lock the UI when you execute the actual delete action and unlock it when the action was completed. The code
```javascript
document.getElementById("masterfset").disabled = false;
```
that is still used in some places for that is deprecated, please use
```javascript
DataMeta.submit.setLock(bool);
```
instead (feel free to refactor the remaining occurrences).

2021-04-21 10:15 UTC, lkuchenb requested changes

2021-04-21 10:15 UTC, lkuchenb commented on datameta/static/js/submit.js
> +    DataMeta.submit.setLock(false);
This has to go after lines 553 and 556, otherwise the UI will be unlocked immediately before the async actions have completed.

2021-04-21 10:15 UTC, lkuchenb commented on datameta/static/js/submit.js
> +        console.log(error)
```suggestion
        console.log(error)
        DataMeta.submit.refresh();
```

2021-04-21 10:15 UTC, lkuchenb commented on datameta/static/js/submit.js
> +    DataMeta.submit.setLock(false);
See above

2021-04-21 11:38 UTC, lkuchenb requested changes

2021-04-21 11:38 UTC, lkuchenb commented on datameta/static/js/submit.js
> +            return DataMeta.submit.refresh();
Same as above

2021-04-21 11:38 UTC, lkuchenb commented on datameta/static/js/submit.js
> +                DataMeta.new_alert("<strong>ERROR</strong> Deleting the files failed: " + json[0].message, "danger");
Same as above

2021-04-21 11:38 UTC, lkuchenb commented on datameta/static/js/submit.js
> +            return DataMeta.submit.refresh();
Your're returning here, the UI never get's unlocked

2021-04-21 11:38 UTC, lkuchenb commented on datameta/static/js/submit.js
> +            response.json().then(json => {
Here's another async call which get's executed in parallel to the unlock below.

You may just want to throw an error in all of the > 400 cases that contains the message. For the 400 case I have added an `AnnotatedError` class, see `refresh()` for an example on how I use it:
https://github.com/ghga-de/datameta/blob/cd2523b68289d6a093ad0e0d9f78c009bf11c7b6/datameta/static/js/submit.js#L461-L488

2021-04-21 15:26 UTC, lkuchenb requested changes

2021-04-21 15:26 UTC, lkuchenb commented on datameta/static/js/submit.js
> +            });
```suggestion
            DataMeta.new_alert("<strong>ERROR</strong> Deleting the files failed: " + error.message, "danger")
            console.log(error.message);
            DataMeta.submit.refresh();
            DataMeta.submit.setLock(false);
```

2021-04-21 15:26 UTC, lkuchenb commented on datameta/static/js/submit.js
> +            });
```suggestion
            DataMeta.new_alert("<strong>ERROR</strong> Deleting the records failed: " + error.message, "danger")
            console.log(error.message);
            DataMeta.submit.refresh();
            DataMeta.submit.setLock(false);
```

2021-04-22 12:56 UTC, lkuchenb approved these changes
Thanks for the changes, feel free to merge!

2021-04-22 13:04 UTC, merged