Added field in the database
ghga-de/datameta pull request #315
Opened 2021-04-23 08:10 UTC by MoritzHahn1337

2021-04-23 10:16 UTC, lkuchenb requested changes

2021-04-23 10:16 UTC, lkuchenb commented on datameta/scripts/initialize_db.py
> +        key='usage_agreement',
```suggestion
        key='user_agreement',
```

2021-04-30 09:52 UTC, lkuchenb commented
Please rebase, I had to pull in the `site_read` fix in #358

2021-04-30 15:04 UTC, lkuchenb requested changes
Thanks for the refactoring! See inline comments and the following:

The error response should be a 401 now. Please remove the `RegistrationResponse` and turn that into a `204`. For errors, use `errors.get_validation_error` as usual. The validation error schema has a `fields` field which we could use for encoding the affected fields, each one needs a message though which could be empty in our case:
```python
errors.get_validation_error(fields=error_fields, messages=['' for _ in error_fields])
```
where `error_fields` is just a list of failed fields (we don't need the bool actually).

2021-05-03 14:24 UTC, lkuchenb commented
@MoritzHahn1337 Please rebase and re-bump the openapi version, I just merged a bump into develop

2021-05-03 16:07 UTC, MoritzHahn1337 commented
> `RegistrationResponse`

Do you mean 400 instead of 401?

2021-05-03 16:07 UTC, MoritzHahn1337 commented
> 
> 
> Thanks for the refactoring! See inline comments and the following:
> 
> The error response should be a 401 now. Please remove the `RegistrationResponse` and turn that into a `204`. For errors, use `errors.get_validation_error` as usual. The validation error schema has a `fields` field which we could use for encoding the affected fields, each one needs a message though which could be empty in our case:
> 
> ```python
> errors.get_validation_error(fields=error_fields, messages=['' for _ in error_fields])
> ```
> 
> where `error_fields` is just a list of failed fields (we don't need the bool actually).

@lkuchenb do you meen 400 isntead of 401?

2021-05-03 16:15 UTC, lkuchenb commented
Yep, sorry, 400

2021-05-04 16:21 UTC, lkuchenb approved these changes
Thanks, just some minor change suggestions below, feel free to merge after fixing

2021-05-04 16:21 UTC, lkuchenb commented on datameta/static/js/register.js
> +                    })
```suggestion
                    var errorFields = json.map(error => error.field);
```

2021-05-04 16:21 UTC, lkuchenb commented on datameta/templates/register.pt
>  		A simple danger alert—check it out!
```suggestion
```

2021-05-04 19:06 UTC, merged