Feature/add password criteria 470
ghga-de/datameta pull request #477
Opened 2021-10-29 12:14 UTC by cschu

2022-01-13 12:13 UTC, lkuchenb requested changes
Thanks, just some minor remarks, see inline comments

2022-01-13 12:13 UTC, lkuchenb commented on datameta/security/__init__.py
> +    PW_MINIMUM_PUNCTUATION = 1
As discussed, please move to app settings

2022-01-14 16:48 UTC, cschu commented
@lkuchenb back to you

2022-01-20 15:30 UTC, lkuchenb approved these changes
@cschu First time we're using non-str values in the appsettings, triggered a bug (the admin page for application settings / the GET endpoint for appsettings didn't load anymore). Fixed in my added commits. Good to merge from my end.

2022-01-20 15:40 UTC, merged

2022-01-20 17:57 UTC, cschu commented
> @cschu First time we're using non-str values in the appsettings, triggered a bug (the admin page for application settings / the GET endpoint for appsettings didn't load anymore). Fixed in my added commits. Good to merge from my end.

I remember there was an issue couldn't recall it was an interface issue. Good that it's solved now..