Add json logger
ghga-de/datameta pull request #497
Opened 2023-01-19 17:55 UTC by ckaipf

PR adds `JsonFormatter ` from `python-json-logger` to enable log serialization.

2023-01-19 17:57 UTC, ckaipf commented on datameta/siteid.py
>      except Exception as e:
Please review, not sure everything is intentionally here

2023-01-20 15:22 UTC, lkuchenb requested changes
Thanks, see remarks and suggestions above!

2023-01-20 15:22 UTC, lkuchenb commented on datameta/api/ui/forgot.py
>      if asbool(threadlocal.get_current_registry().settings['datameta.logging.log_token_urls']):
As discussed, feel free to remove the check

2023-01-20 15:22 UTC, lkuchenb commented on datameta/api/ui/forgot.py
> +        log.debug("User requsted recovery token.", extra={"token_url": token_url})
Let's keep this the same style as with the forgot_api call

2023-01-20 15:22 UTC, lkuchenb commented on datameta/email/__init__.py
> +        log.error("Email sending exception.", extra={"exception": e})
```suggestion
        log.error("SMTP error.", extra={"error": e})
```

2023-01-20 15:22 UTC, lkuchenb commented on datameta/siteid.py
> +            log.warning("Site ID collision, ID space may saturates.", extra={"tablename": BaseClass.__tablename__})
```suggestion
            log.warning("Site ID collision, ID space may be saturating.", extra={"tablename": BaseClass.__tablename__})
```

2023-01-20 15:22 UTC, lkuchenb commented on datameta/views/login.py
> +                log.info("Login.", extra={"user_id": auth_user.id, "email": auth_user.email, "client_addr": request.client_addr})
```suggestion
                log.info("User logged in.", extra={"user_id": auth_user.id, "email": auth_user.email, "client_addr": request.client_addr})
```

2023-01-23 09:26 UTC, lkuchenb approved these changes

2023-01-23 10:02 UTC, merged