Unique constraint none
ghga-de/datameta pull request #509
Opened 2023-02-15 14:14 UTC by ckaipf

- This PR updates the validation of the site and submission unique property
- MetaDatum which are unique (and not mandatory) should not evaluate values set to None for unique constraint

2023-02-15 14:47 UTC, ckaipf commented
I think that should only affect MetaDatum which are not mandatory, otherwise we will get an error anyway when value is empty or None

2023-02-20 11:18 UTC, lkuchenb requested changes

2023-02-20 11:18 UTC, lkuchenb commented on datameta/validation.py
> +        not_unique = [ v for v in value_msets.values() if len(v) > 1 ]
```suggestion
        not_unique = ( v for v in value_msets.values() if len(v) > 1 )
```
No list needed, can use a generator here.

2023-02-20 11:18 UTC, lkuchenb commented on datameta/validation.py
> +                    if mdatrec.value is not None:
Could just be an `and` clause with the previous `if` condition, plain nested `if`s look somewhat funny IMHO

2023-02-20 11:18 UTC, lkuchenb commented on datameta/validation.py
> +                    if mdatrec.value is not None:
see above

2023-02-20 16:21 UTC, lkuchenb approved these changes

2023-02-21 07:39 UTC, merged