Implemented ApiKey REST interface
ghga-de/datameta pull request #92
Opened 2021-02-24 17:19 UTC by KerstenBreuer

First draft of the REST interface with ApiKey handling.

2021-02-24 17:30 UTC, KerstenBreuer commented
@lkuchenb, any idea why the `datameta/api/openapi.yaml` is not found in the testing setup?

2021-02-24 17:34 UTC, lkuchenb commented
Probably not installed with the python package, that's something that's easy to miss when you develop with `-e`. It would need to go into the `MANIFEST.in` file then.

2021-02-24 17:38 UTC, KerstenBreuer commented
Great, now it works, thanks @lkuchenb

2021-02-24 17:47 UTC, KerstenBreuer commented
By the way, you can see the swagger UI at http://localhost:8080/api 😄

2021-02-25 08:12 UTC, MoritzHahn1337 approved these changes
As far as my limited knowledge goes, this looks good.

2021-02-25 13:27 UTC, KerstenBreuer commented
@lkuchenb, I implemented the changes we discuss so that the apikey post can also be used when relying on cookies.

Could you please have another look?

2021-02-25 17:30 UTC, KerstenBreuer commented
Following changes:
- Validation errors are now forwarded as correct response
- the application/json is now required but the properties (emails and passwords) are not when used from a cookie-base loggedin browser (you can simply provide an empty json as request)

@lkuchenb , @MoritzHahn1337 to try it out (or implement) in the frontend, something like this will work:
```
fetch(
    'http://localhost:8080/api/keys', 
    {
        method: "POST",
        body: JSON.stringify({}),
        headers: {
        "Content-type": "application/json; charset=UTF-8"
   }
})
   .then(res => res.json())
   .then(console.log)
```

I hope this is fine.

2021-02-25 17:38 UTC, MoritzHahn1337 approved these changes

2021-02-25 20:37 UTC, lkuchenb requested changes

2021-02-25 20:37 UTC, lkuchenb commented on datameta/api/apikeys.py
> +        comment = "",
This should be implemented

2021-02-26 07:35 UTC, KerstenBreuer commented on datameta/api/apikeys.py
> +        comment = "",
@lkuchenb, what do you mean by that?

2021-02-26 09:54 UTC, lkuchenb approved these changes

2021-02-26 10:35 UTC, merged